site_name: My Docs
theme:
  name: material
  language: ru
  font:
    # text: Shantell Sans
    text: Raleway
  features:
    - content.tabs.link
extra:
  homepage: https://docs.hbf.fraima.io

copyright: >
  Copyright &copy; 2022 - 2023 Dobry_kot

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      auto_title: true

  - toc:
      permalink: true
      title: On this page
      permalink_title: Anchor link to this section for reference
      toc_depth: 3
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg   
  - tables
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
   - swagger-ui-tag

nav:
  - About: index.md
  - Describe: introduction.md
  - Quick Install: quick_installation.md
  - Swagger: swagger.md
  - Trubleshooting: trubleshooting.md

extra_css:
  - stylesheets/extra.css