site_name: My Docs
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  language: en
  font:
    # text: Shantell Sans
    text: Raleway
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotate 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.instant
    # - header.autohide
    - navigation.footer
    # - content.action.edit
extra:
  homepage: https://docs.hbf.fraima.io

repo_url: https://github.com/H-BF/sgroups
repo_name: H-BF/sgroups

copyright: >
  Copyright &copy; 2022 - 2023 Dobry_kot

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      auto_title: true

  - toc:
      permalink: true
      title: On this page
      permalink_title: Anchor link to this section for reference
      toc_depth: 3
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg   
  - tables
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - swagger-ui-tag
  - search
  # Добавляет в конце страницы информацию по дате создания и обновлению
  # - git-revision-date-localized:
  #     enable_creation_date: true

nav:

  - About: 
    - index.md
    - ToolSet: toolset.md
  
  - Getting started: 
    - Installation: quick_installation.md
    - Setup: quick_start.md
    - Trubleshooting: trubleshooting.md
    
  - Swagger: swagger.md
  

extra_css:
  - stylesheets/extra.css


