site_name: My Docs
theme:
  name: material
  language: ru
  font:
    # text: Shantell Sans
    text: Raleway
  features:
    - content.tabs.link
extra:
  homepage: https://docs.fraima.io

copyright: >
  Copyright &copy; 2022 - 2023 Dobry_kot

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      auto_title: true

  - md_in_html
  - toc:
      permalink: true
      title: On this page
      permalink_title: Anchor link to this section for reference
      toc_depth: 3
  - tables
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
   - swagger-ui-tag